[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "goto_conversion"
version = "2.0.2"
authors = [{ name = 'Kaito Goto' },]
description = "Gambling Odds To Outcome probabilities Conversion (goto_conversion)"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/gotoConversion/goto_conversion"
"Bug Tracker" = "https://github.com/gotoConversion/goto_conversion/issues"
